### ISSUE TITLE
Parsing of escaped quotes

### ISSUE THREAD

**Issue by zevv** [SolitudeSF/shlex#1]
This seems to drop the escaped quotes from the string:
```
check shlex("foo\"bar\"baz") == (false, @["foobarbaz"])
```
Should that not output `@["foo\"bar\"baz"]` instead?

**Comment by SolitudeSF** [comment]
this works as intended.
```sh
$ echo foo"bar"baz
foobarbaz
```
`shlex` kinda implies that we try to mimic shells behavior.

**Comment by zevv** [comment]
Ah right, makes sense. Sorry for the noise!
